// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAK5sl4cW-_J4evLN4YPchTTyRfweVlOo',
    appId: '1:819133994826:web:110885f6e0ea5f66d353b3',
    messagingSenderId: '819133994826',
    projectId: 'qahwati-ffe45',
    authDomain: 'qahwati-ffe45.firebaseapp.com',
    storageBucket: 'qahwati-ffe45.firebasestorage.app',
    measurementId: 'G-C5EKDC7JZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4PNOH92ZfZE53WsxxAkMY0Wkg9SZ3Lu0',
    appId: '1:819133994826:android:7be7c7dfbb0f2ed7d353b3',
    messagingSenderId: '819133994826',
    projectId: 'qahwati-ffe45',
    storageBucket: 'qahwati-ffe45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACCmi1yRq2YuUZ40KmA73WFqvWNcY53RA',
    appId: '1:819133994826:ios:a6d9d7575ce2a075d353b3',
    messagingSenderId: '819133994826',
    projectId: 'qahwati-ffe45',
    storageBucket: 'qahwati-ffe45.firebasestorage.app',
    iosBundleId: 'com.example.qahwati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACCmi1yRq2YuUZ40KmA73WFqvWNcY53RA',
    appId: '1:819133994826:ios:a6d9d7575ce2a075d353b3',
    messagingSenderId: '819133994826',
    projectId: 'qahwati-ffe45',
    storageBucket: 'qahwati-ffe45.firebasestorage.app',
    iosBundleId: 'com.example.qahwati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAK5sl4cW-_J4evLN4YPchTTyRfweVlOo',
    appId: '1:819133994826:web:0692299a36e3a8b6d353b3',
    messagingSenderId: '819133994826',
    projectId: 'qahwati-ffe45',
    authDomain: 'qahwati-ffe45.firebaseapp.com',
    storageBucket: 'qahwati-ffe45.firebasestorage.app',
    measurementId: 'G-P84S5M5G2E',
  );
}
